---
apiVersion: v1
kind: Service
metadata:
  name: bankfast-load-balancer
spec:
  ports:
    - port: 12000
      targetPort: 12000
  selector:
    app: bankfast-load-balancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankfast-load-balancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankfast-load-balancer
  template:
    metadata:
      labels:
        app: bankfast-load-balancer
    spec:
      containers:
        - image: {{ .Values.loadBalancer.imageName }}
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
          imagePullPolicy: Always
          name: bankfast-load-balancer
          env:
            - name: CONFIG_FILE
              value: "bf-haproxy.cfg"
            # - name: LOG_LEVEL
            #   value: "info"
          ports:
            - containerPort: 12000
          livenessProbe:
            tcpSocket:
              port: 12000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 2
          readinessProbe:
            tcpSocket:
              port: 12000
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
      imagePullSecrets:
        - name: dc-cdtbm
