---
apiVersion: v1
kind: Service
metadata:
  name: bfsi
spec:
  ports:
    - name: http
      port: 55000
      targetPort: 55000
    - name: https
      port: 55003
      targetPort: 55003
  selector:
    app: bfsi
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bfsi-auto-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bfsi
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 1000Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bfsi
spec:
  selector:
    matchLabels:
      app: bfsi
  template:
    metadata:
      labels:
        app: bfsi
    spec:
      containers:
          # revert to 0.6.0 if there are errors acquiring a connection to bfsi
        - image: {{ .Values.bfsi.imageName }}
          imagePullPolicy: Always
          name: bfsi
          ports:
            - containerPort: 55000
            - containerPort: 55003
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /getTermsAndConditions
              port: 55000
            initialDelaySeconds: 150
            periodSeconds: 60
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /getTermsAndConditions
              port: 55000
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 10
      imagePullSecrets:
        - name: dc-cdtbm
