---
apiVersion: v1
kind: Service
metadata:
  name: elevate-connector
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: elevate-connector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevate-connector
spec:
  selector:
    matchLabels:
      app: elevate-connector
  template:
    metadata:
      labels:
        app: elevate-connector
    spec:
      containers:
        - name: elevate-connector
          image: {{ .Values.elevateConnector.imageName }}
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: APPOINTMENT_MANAGER_URL
              value: {{ .Values.external.appointmentManagerUrl }}
            - name: APPOINTMENT_MANAGER_CONTEXT_ROOT
              value: {{ .Values.external.appointmentManagerContextRoot }}
            - name: APPLY_BASE_URL
              value: {{ .Values.external.applyBaseUrl }}
            - name: IB_BASE_URL
              value: https://{{ template "host.external" . }}
            - name: CHAT_BOT_URL
              value: {{ .Values.external.chatbotUrl }}
            - name: CHAT_BOT_CONTEXT_ROOT
              value: {{ .Values.external.chatbotContextRoot }}
            - name: PFM_BASE_URL
              value: {{ .Values.external.pfmBaseurl }}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dc-cdtbm
