---
apiVersion: v1
kind: Service
metadata:
  name: portal-load-balancer
spec:
  ports:
    - name: internalport
      port: 8081
      targetPort: 8081
    - name: externalport
      port: 8082
      targetPort: 8082
    - name: sstinternalport
      port: 8083
      targetPort: 8083
  selector:
    app: portal-load-balancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-load-balancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-load-balancer
  template:
    metadata:
      labels:
        app: portal-load-balancer
    spec:
      containers:
        - env:
            - name: CONFIG_FILE
              value: "portal-haproxy.cfg"
          image: {{ .Values.loadBalancer.imageName }}
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
          imagePullPolicy: Always
          name: portal-load-balancer
          ports:
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8083
      imagePullSecrets:
        - name: dc-cdtbm
