---
apiVersion: v1
kind: Service
metadata:
  name: waf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: waf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: waf
  template:
    metadata:
      labels:
        app: waf
    spec:
      containers:
        - name: waf
          image: {{ .Values.waf.imageName }}
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: APPOINTMENT_MANAGER_URL
              value: {{ .Values.external.appointmentManagerUrl }}
            - name: APPOINTMENT_MANAGER_CONTEXT_ROOT
              value: {{ .Values.external.appointmentManagerContextRoot }}
            - name: CHAT_BOT_URL
              value: {{ .Values.external.chatbotUrl }}
            - name: CHAT_BOT_CONTEXT_ROOT
              value: {{ .Values.external.chatbotContextRoot }}
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "500Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
      imagePullSecrets:
        - name: dc-cdtbm
