---
apiVersion: v1
kind: Service
metadata:
  name: fakehost
spec:
  ports:
    - name: host
      port: 12018
      targetPort: 12018
    - name: npp
      port: 40712
      targetPort: 40712
    - name: estatments
      port: 40710
      targetPort: 40710
  selector:
    app: fakehost
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakehost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fakehost
  template:
    metadata:
      labels:
        app: fakehost
    spec:
      containers:
        - image: {{ .Values.fakehost.image }}
          imagePullPolicy: Always
          name: fakehost
          ports:
            - containerPort: 12018
            - containerPort: 40712
            - containerPort: 40710
      imagePullSecrets:
        - name: dc-cdtbm
